### PR TITLE
Angular -> Mustache-y Components

### PR DESCRIPTION
**Pull request by caseywatts**
This pull request does a lot at once:
- remove dependency on angular
- use meetup_cards.html from techcorridor.io (and installed jquery, bootstrap, and underscore which it depends on)
- remove "community" and "photos" sections and the retrocession announcement
- extract content to partials, remove some unused files

I talked with @csexton this morning about these details, he thumbs-upped these ideas generally. I did a lot in this PR, I certainly won't be surprised if you or anyone else have feedback about the changes before merging :)

Also, thanks to @benjaminoakes for his work on techcorridor.io that inspired this and @uncompiled for getting `meetup_card.html` all set up :D
I learned a lot about structuring reusable "web components" (lol) while thinking about this PR, it's been good for me too~

image

### CODE REVIEW

**Comment by caseywatts** [comment]
Also made a "jumbotron" and link buttons

image

**Comment by caseywatts** [comment]
I've been focusing on the layout mostly, this could use more style work (also css is not my specialty lol).

**Comment by SeanMarcia** [comment]
:+1: :heart: :+1:

**Comment by benjaminoakes** [comment]
Happy to hear [techcorridor.io](http://techcorridor.io) could help.  :smile:  I'd be glad to continue to collaborate.

**Comment by jwieringa** [comment]
@caseywatts++ :+1:

**Pull request merged**
